image:
  repository: busybox
  tag: latest

seed:
  enabled: true
  debug: false
  sqlConfigMapName: ""
  checksum: ""
  sqlMountPath: /app/sql

database:
  engine: postgres
  host: localhost
  port: 5432
  name: mydatabase
  user: dbuser
  password: dbpassword

logging:
  level: info

# Resources maybe?