seed:
  enabled: true
  debug: true
  sqlMountPath: ./sql
database:
  engine: postgres
  host: localhost
  port: 5432
  name: mydatabase
  # username: user -> Are set via environment variables, check the Makefile
  # password: pass -> same as above
logging:
  level: INFO