apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fullname" . }}-config
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |-
    seed:
      enabled: {{ .Values.seed.enabled }}
      debug: {{ .Values.seed.debug }}
    database:
      engine: {{ .Values.database.engine }}
      host: {{ .Values.database.host }}
      port: {{ .Values.database.port }}
      name: {{ .Values.database.name }}
    