apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fullname" . }}-config
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |-
    seed:
      enabled: {{ .Values.seed.enabled }}
      debug: {{ .Values.seed.debug }}
      sqlMountPath: {{ .Values.seed.sqlMountPath }}
    database:
      engine: {{ .Values.database.engine }}
      host: {{ .Values.database.host }}
      port: {{ .Values.database.port }}
      database: {{ .Values.database.database }}
      sslmode: {{ .Values.database.sslmode }}

    logging:
      level: {{ .Values.logging.level | default "INFO" | upper }}